Database implementation ᕦ(ò_óˇ)ᕤ
Diary-SPO/api pull request #14
Opened 2023-11-22 11:31 UTC by Zamelane

Implementation of the database, token system and cookie updates

2023-11-23 15:02 UTC, scffs requested changes

2023-11-23 15:02 UTC, scffs commented on src/types/database/index.ts
> +}
удалить и брать из https://github.com/Diary-SPO/types

2023-11-23 15:02 UTC, scffs commented on src/utils/cookieExtractor.ts
> +export const cookieExtractor = (setCookieHeader: string) => {
тип возвращаемого значения не указан

2023-11-23 15:02 UTC, scffs commented on src/worker.ts
> +declare var self: Worker
запрещаю использовать var

2023-11-23 15:02 UTC, scffs commented on src/worker.ts
> +}
Давай разделим на разные функции и код будет намного лучше. функции можно положить рядом с воркером

2023-11-23 15:02 UTC, scffs commented on src/worker.ts
> +function messageNext() {
мы обычно `const name = () => {}` используем

2023-11-23 15:03 UTC, scffs commented on src/database/getCookieFromToken.ts
> +        const actualSeconds = new Date().getTime() / 1000
хотя в целом неважно

2023-11-24 06:23 UTC, scffs requested changes
`bun serve` перестала работать

2023-12-03 14:10 UTC, Zamelane commented on src/database/registration.ts
> +    const regSPO: SPO = {
~~Он же потом используется для вставки ?
А если существует, то в базе обновляется этим объектом как актуальными данными и вписывается в него же id, чтобы получить целостную запись из БД ?~~

Чтобы меньше места занимало ?
Не вставить же ответ от сервера напрямую, т.к. там лишние записи... А с этим объектом работаем несколько раз, так что расписывать его при каждом использовании такая себе идея ...

2023-12-03 14:10 UTC, Zamelane commented on src/database/registration.ts
> +    const actualSPO: SPO = regSPO
Поправил

2023-12-28 11:41 UTC, scffs requested changes

2023-12-29 14:34 UTC, scffs requested changes

2023-12-29 14:34 UTC, scffs commented on src/routes/hello/getGitCommitHash.ts
> +}
линтом не прошелся

2023-12-30 09:03 UTC, scffs requested changes

2023-12-30 09:03 UTC, scffs commented on src/srcWorker/cookieUpdater/config.ts
> +export const maxNotUpdateTokenInDays = 5
такие константы называются в стиле `LIKE_THIS_EXAMPLE_AAAA`

2023-12-30 09:03 UTC, scffs commented on src/routes/performance.current/index.ts
> +  headers: t.Object({
ты уверен, что он умеет с headers работать?

2023-12-30 09:03 UTC, scffs commented on src/routes/login/handler.ts
> +  // Захешировать пароль ? (Для отладки, потом можно вырезать)
не пора вырезать?

2023-12-30 09:03 UTC, scffs commented on src/routes/hello/getServerInfo.ts
> +    arch: process.arch,
зачем?

2023-12-30 09:03 UTC, scffs commented on src/database/registration.ts
> +    regData.groupId = regGroup?.id ?? -1 // <- ???
??

2024-01-01 16:31 UTC, Zamelane commented on src/routes/performance.current/index.ts
> +  headers: t.Object({
Да

2024-01-01 16:31 UTC, Zamelane commented on src/routes/login/handler.ts
> +  // Захешировать пароль ? (Для отладки, потом можно вырезать)
Не-а :)

2024-01-01 16:32 UTC, Zamelane commented on src/routes/hello/getServerInfo.ts
> +    arch: process.arch,
Ключевое поле для проверки работоспособности в мониторинге

2024-01-01 16:32 UTC, Zamelane commented on src/database/registration.ts
> +    regData.groupId = regGroup?.id ?? -1 // <- ???
Что-то с типами...

2024-01-01 17:36 UTC, scffs approved these changes

2024-01-01 17:37 UTC, merged