Интеграция базы данных
Diary-SPO/api pull request #18
Opened 2024-01-09 14:29 UTC by Zamelane

Сохранение и возвращение следующей информации в случае падения оригинального дневника:
* Расписание
   * Преподаватели
   * Задания
   * Типы заданий
   * Темы
   * Типы тем
   * Пары на каждый день
* Успеваемость
   * Оценки
   * Обязательность выполнения заданий (получения оценки)

2024-01-09 14:53 UTC, scffs requested changes

2024-01-09 14:53 UTC, scffs commented on src/database/lessons.ts
> +    const userInfo: DiaryUser | null = await getDiaryUser(userId)
тип указывать необязательно, он автоматом будет

2024-01-09 14:53 UTC, scffs commented on src/database/lessons.ts
> +                updatingLessons.push(dbLesson)
как-то можно от вложенности if'ов избавиться?

2024-01-09 14:53 UTC, scffs commented on src/database/tables/groups/get.ts
> +export const getGroupInfo = async (
getGroupInfoByGroupId

2024-01-09 14:53 UTC, scffs commented on src/database/tables/schedule/save.ts
> +    const teacher: DBTeacher = await saveTeacher(schedule.timetable.teacher, groupInfo.spoId)
тип необязателен и вроде тип DBTeacher лишний, сам знаешь

2024-01-09 14:53 UTC, scffs commented on src/types/databaseTypes/index.ts
> +export interface DBSchedule {
точно ли у нас уже нет похожего типа?

2024-01-09 15:00 UTC, scffs requested changes

2024-01-09 16:55 UTC, scffs requested changes

2024-01-09 16:55 UTC, scffs commented on src/types/index.ts
> +  commit: string
неее

2024-01-10 03:11 UTC, Zamelane commented on src/types/index.ts
> +  commit: string
Даааа 😂

2024-01-30 13:09 UTC, scffs commented
see https://github.com/Diary-SPO/web/pull/126

2024-01-30 13:09 UTC, closed without merging