Init
Diary-SPO/api pull request #21
Opened 2024-01-20 12:40 UTC by Zamelane

2024-01-20 19:59 UTC, scffs requested changes

2024-01-20 19:59 UTC, scffs commented on src/database/auth.ts
> +import { GroupsModel } from './models'
В чем прикол?

2024-01-20 19:59 UTC, scffs commented on src/database/models/diaryUser.ts
> +export const DiaryUserModel = () => DiaryUser
Почему нельзя просто модель вернуть?

2024-01-20 19:59 UTC, scffs commented on src/database/registration.ts
> -      cookie: encrypt(cookie ?? '', ENCRYPT_KEY),
?

2024-01-20 19:59 UTC, scffs commented on src/database/registration.ts
> -      password: encrypt(password ?? '', ENCRYPT_KEY),
?

2024-01-21 03:51 UTC, Zamelane commented on src/database/auth.ts
> +import { GroupsModel } from './models'
Не понял

2024-01-21 03:53 UTC, Zamelane commented on src/database/registration.ts
> -      cookie: encrypt(cookie ?? '', ENCRYPT_KEY),
Теперь в геттерах и сеттерах, см. [тут](https://github.com/Diary-SPO/api/blob/new-database-provider/src/database/models/diaryUser.ts#L68)

2024-01-21 03:54 UTC, Zamelane commented on src/database/registration.ts
> -      password: encrypt(password ?? '', ENCRYPT_KEY),
Теперь в геттерах и сеттерах, см. [тут](https://github.com/Diary-SPO/api/blob/new-database-provider/src/database/models/diaryUser.ts#L32)

2024-01-21 03:55 UTC, Zamelane commented on src/database/auth.ts
> +import { GroupsModel } from './models'
Это чтобы связи установить, смотри низ файла

2024-01-21 04:29 UTC, Zamelane commented on src/database/auth.ts
> +import { GroupsModel } from './models'
А, ой. Не знаю, почему так импорты получились

2024-01-21 18:42 UTC, scffs approved these changes

2024-01-21 18:42 UTC, merged